language: go
os:
  - linux
  - osx
go:
  - "1.10.1"
before_install:
  - go get github.com/docopt/docopt-go
branches:
  only:
    - docopts-go
    - master
notifications:
  email:
    on_success: never
script:
  - make test
