language: go
os:
  - linux
  - osx
go:
  - "1.11.4"
  - "1.13"
before_install:
  # brew update takes very long time
  # according to https://docs.travis-ci.com/user/reference/osx#homebrew
  # homebrew is already updated
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash; fi
  - bash --version ; type bash
  - go get github.com/docopt/docopt-go
  # get our official repos too
  - go get github.com/docopt/docopts
branches:
  only:
    - docopts-go
    - master
notifications:
  email:
    on_success: never
script:
  - make test
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/reverse_ssh_tunnel.sh ; fi
