language: go
go:
  - "1.10.1"
before_install:
  - go get github.com/docopt/docopt-go
branches:
  only:
    - docopts-go
notifications:
  email:
    on_success: never
script:
  - go build docopts.go
  - go test -v .
  - python language_agnostic_tester.py ./testee.sh
